#25 Implemented a blacklist for BaseApps
tchx84/Flatseal pull request #27
Opened 2020-02-09 18:14 UTC by Eonfge

See issue #25 where I mentioned this minor issue

2020-02-09 21:26 UTC, tchx84 requested changes

2020-02-09 21:26 UTC, tchx84 commented on src/model.js
> +    'org.mozilla.Firefox.BaseApp'
I don't think maintaining a hard coded list of app-ids would scale well. But, we could add a `isBaseApp()` method though, which could translate to ` return appId.endsWith('.BaseApp')`.

A bit of a hack, but I think is a decent trade-off considering `.BaseApp` is a well established convention at this point.

2020-02-10 08:17 UTC, Eonfge commented
I first had that, but I wish to argue that it's better to a limited blacklist of hard defined app slugs.

See, there could also be other Flatpak providers then Flathub, and they are in no way obliged to follow the same naming schematic. See [Nuvola](https://nuvola.tiliado.eu/) for example. As such, it's better to cast a net that occasionally has a false negative, then a false positive: Better not block one BaseApp from an unknown third party repository, then to block legitimate apps because string validations are inherently messy.

So, while we're add it, shall we also add `eu.tiliado.NuvolaBase` to the blacklist?

2020-02-10 11:03 UTC, tchx84 commented
> I first had that, but I wish to argue that it's better to a limited blacklist of hard defined app slugs.
> 
> See, there could also be other Flatpak providers then Flathub, and they are in no way obliged to follow the same naming schematic. See [Nuvola](https://nuvola.tiliado.eu/) for example. As such, it's better to cast a net that occasionally has a false negative, then a false positive: Better not block one BaseApp from an unknown third party repository, then to block legitimate apps because string validations are inherently messy.
> 
> So, while we're add it, shall we also add `eu.tiliado.NuvolaBase` to the blacklist?

I rather see those .BaseApp in the app, which are innocuous, rather than adding the burden of maintaining a hard-coded list. You said it yourself, there could be many providers, and having a hard-coded list is just a mouse cat chase game.

2020-02-10 19:26 UTC, tchx84 requested changes
Plus, can you add a test for this new behavior? 

Basically, just add something like https://github.com/tchx84/Flatseal/tree/master/tests/content/system/flatpak/app/com.test.Example/current/active to the `tests/content` directory. Call it `com.test.BaseApp` and add a specific test in `tests/src/model.js`  to check that is the app-id is properly ignored.

2020-02-10 19:26 UTC, tchx84 commented on src/model.js
> +            if (GLib.access(activePath, 0) === 0 && appId.endsWith(".BaseApp") == false)
Can you:
1. Invert the order? Check for `.BaseApp` first. One disk access less ;)
2. Use single quotes.
3. Add a `/* XXX will only work with app-ids that follow the BaseApp convention */` (or whatever message you seem fit).

2020-02-10 19:28 UTC, tchx84 commented
Also, if you are not convince about this approach either,  you could research a bit more and see if there is another way to detect this condition. But if you're out of time, this will be fine for now.

2020-02-13 16:39 UTC, Eonfge commented
Added the comment. Considering the size and relevance of this feature, I think it's good enough for now.

2020-02-14 19:44 UTC, tchx84 commented
I appreciate your feedback and interest in contributing to the project, but let me be clear; I can't accept contributions that won't consider such basic requirements like adding a simple test for a new behavior.

2020-02-14 19:44 UTC, closed without merging