Add feature --allow=per-app-dev-shm
tchx84/Flatseal pull request #342
Opened 2021-10-17 10:12 UTC by Arxcis

## Why?

From Flatpak 1.11.1 [release notes](https://github.com/flatpak/flatpak/releases/tag/1.11.1):
>- Instances of the same app-ID can optionally share their /dev/shm directory
(enabled by a new --allow flag, --allow=per-app-dev-shm)

## TODO 
- [ ] Build
    ```sh
    ~/git/github.com/Arxcis/Flatseal$ meson build
    The Meson build system
    Version: 0.56.2
    Source dir: /home/jonas/git/github.com/Arxcis/Flatseal
    Build dir: /home/jonas/git/github.com/Arxcis/Flatseal/build
    Build type: native build
    Project name: flatseal
    Project version: 1.7.4
    Host machine cpu family: x86_64
    Host machine cpu: x86_64
    WARNING: Gettext not found, all translation targets will be ignored.
    
    data/meson.build:1:0: ERROR: Tried to assign an invalid value to variable.
    
    A full log can be found at /home/jonas/git/github.com/Arxcis/Flatseal/build/meson-logs/meson-log.txt
    ```
- [ ] Test  ?

2021-10-18 10:21 UTC, tchx84 requested changes
hey @Arxcis ! Thanks for working on this, just a few minor comments.

2021-10-18 10:21 UTC, tchx84 commented on tests/src/testModels.js
> +        expect(permissions.features_per_app_dev_shm).toBe(true);
For this to actually work, you need to add this permission to the test permission files. Check which appId is used by this test to find the proper file.

2021-10-18 10:21 UTC, tchx84 commented on src/models/features.js
> +                description: _('Per app /dev/shm'),
Shared Memory per Application?

2021-10-19 17:34 UTC, Arxcis commented on tests/src/testModels.js
> +        expect(permissions.features_per_app_dev_shm).toBe(true);
Maybe fixed in fe451a1

2021-10-19 17:34 UTC, Arxcis commented on src/models/features.js
> +                description: _('Per app /dev/shm'),
Maybe fixed in fe451a1

2021-10-19 17:47 UTC, Arxcis commented on src/models/features.js
> +                description: _('Per app /dev/shm'),
Yes. Good suggestion :+1:  Since you asked, I have a few more in my head :sweat_smile: :

**Suggestions** :thinking: 
- Shared Memory per Application (credit to @tchx84)
- Shared Memory by Application
- Per Application Shared Memory 
- Shared Memory between Application instances
- Application instances share memory
- Application scoped Shared Memory
- Application specific Shared Memory
- Application owned Shared Memory
- Application local Shared Memory
- Application Shared Memory           

The last one here is my favorite, because it is similar to "Host Shared Memory", which is a concept I already understand :exclamation:

`(Host|Application) Shared Memory`:
- `(Host|Application)` - refers to the scoping of the Shared Memory. 
    - `Host` scope - Means the shared memory is accessible from anywhere on the host system, and from Flatpaks which have opened the hole --device=shm. 
    - `Application` scope - Means the shared memory is only accessible from instances of the same application.
- `Shared Memory` - refers to `/dev/shm`
- Example usage: 
    >"I have put the pipe in `Application Shared Memory`, so it is accessible from any instance of my application". 
    >"Oh, you should have put the pipe in `Host Shared Memory` instead, because I want easy access to it on the host."

2021-10-19 19:03 UTC, Arxcis commented on src/models/features.js
> +                description: _('Per app /dev/shm'),
Fix in f363a39

2021-10-19 20:19 UTC, tchx84 commented
@Arxcis  You need to increase some counters in the test files :)

2021-10-19 20:48 UTC, Arxcis commented
> @Arxcis You need to increase some counters in the test files :)

Done :sweat_smile:

2021-10-20 10:04 UTC, tchx84 commented
There's still one counter off ! It seems.

2021-10-20 15:59 UTC, Arxcis commented
> There's still one counter off ! It seems.

Sorry. I don't know how to run the tests locally before I push. Fix here 88740f9

2021-10-20 18:12 UTC, tchx84 commented
This might give you some hints for running it locally https://github.com/tchx84/gtk-apps-testing-docker-action/blob/gjs/Dockerfile

2021-10-20 18:13 UTC, tchx84 requested changes
Tests still failing...

2021-10-20 21:34 UTC, Arxcis commented
> This might give you some hints for running it locally https://github.com/tchx84/gtk-apps-testing-docker-action/blob/gjs/Dockerfile

Ok. Thank you. I will look into it👍

2021-10-21 20:47 UTC, merged

2021-10-21 20:47 UTC, tchx84 commented
This is looking great now, thanks @Arxcis :)