po: Add French translation
tchx84/Flatseal pull request #367
Opened 2021-11-07 17:03 UTC by TheEvilSkeleton

2021-11-07 17:18 UTC, AsciiWolf commented
The [LINGUAS](https://github.com/tchx84/Flatseal/blob/master/po/LINGUAS) file should probably be updated as well.

2021-11-07 17:38 UTC, TheEvilSkeleton commented
Thanks.

2021-11-07 20:18 UTC, TheEvilSkeleton commented
How would I go about testing it out? I read through the documentation and I realized how extremely unclear the "Add new translations" section is.

2021-11-08 10:32 UTC, tchx84 commented
> How would I go about testing it out? I read through the documentation and I realized how extremely unclear the "Add new translations" section is.

How about this, copy the documentation instructions here and we go one by one... ?

Now, re. the tests, the CI logs show multiple instances of the following error:
```
../data/../po/fr.po:29:10: invalid multibyte sequence
```

2021-11-08 14:34 UTC, TheEvilSkeleton commented
> > How would I go about testing it out? I read through the documentation and I realized how extremely unclear the "Add new translations" section is.
> 
> How about this, copy the documentation instructions here and we go step by step... ? Let's see what can be improved.

I'm at the step when you have to launch the app, which can be found [here](https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#:~:text=Add%20a%20new,strings%20to%20Spanish), I ran:

```
$ flatpak config --set languages fr
$ flatpak update org.gnome.Platform
$ LC_ALL=fr_CA.UTF-8 flatpak run com.github.tchx84.Flatseal
```

`flatpak update org.gnome.Platform` did work but I get the following error:

```
 1. [✗] org.freedesktop.Platform.GL.default            21.08             u            flathub           < 128.6 MB
 2. [✗] org.freedesktop.Platform.openh264              2.0               u            flathub             < 1.5 MB

Warning: Server returned status 404: Not Found
Warning: Server returned status 404: Not Found

```

The program launched without a problem, however it wasn't in French.

> Now, re. the tests, the CI logs show multiple instances of the following error:
> 
> ```
> ../data/../po/fr.po:29:10: invalid multibyte sequence
> ```

Switching to UTF-8 successfully compiled, not sure why it was using ASCII.

2021-11-08 20:20 UTC, tchx84 requested changes

2021-11-08 20:20 UTC, tchx84 commented on po/fr.po
> +msgstr "À propos de Flatseal"
You're missing the  mnemonic `_` mark, e.g. it could be `À propos de _Flatseal`, but it should be different for each marked string.

2021-11-08 20:20 UTC, tchx84 commented on po/fr.po
> +msgstr "_Réinitialiser"
You're already using `_R` in a previous string.

2021-11-08 21:05 UTC, TheEvilSkeleton commented
It looks like the issue still persists.

2021-11-08 21:09 UTC, tchx84 commented
> It looks like the issue still persists.

I tested it locally, and seems to work fine...

![image](https://user-images.githubusercontent.com/481418/140818330-9e913e4f-bffb-4071-9cbd-0b626e83fba0.png)

Are you sure you're running your own version? Built from your branch?

2021-11-08 21:09 UTC, tchx84 commented
Just mark it as ready.

2021-11-08 21:09 UTC, tchx84 commented
Try running it with

```
LC_ALL=fr_CA.UTF-8 flatpak run com.github.tchx84.Flatseal//master
```

2021-11-08 21:12 UTC, TheEvilSkeleton commented
> Try running it with
> 
> ```
> LC_ALL=fr_CA.UTF-8 flatpak run com.github.tchx84.Flatseal//master
> ```

That doesn`t exist because I use the `//localtest` branch. Although I ran it with the `//localtest` branch and it still doesn't work

2021-11-08 21:16 UTC, tchx84 approved these changes

2021-11-08 21:16 UTC, merged

2021-11-08 21:20 UTC, tchx84 commented
good job! Thanks.

PS: you should probably follow the build-from-source instructions from the README

2021-11-08 23:23 UTC, TheEvilSkeleton commented
Ah okay.