Adding Hebrew translation
tchx84/Flatseal pull request #434
Opened 2022-05-17 14:34 UTC by yarons

2022-05-17 23:47 UTC, tchx84 requested changes
Hey, thanks for the translation, but you also need to add this file name to `po/LINGUAS`

2022-05-18 01:08 UTC, TheEvilSkeleton requested changes
Above these suggestions there is a comment saying to not translate this message.

2022-05-18 01:08 UTC, TheEvilSkeleton commented on po/he.po
> +msgstr "Flatseal"
```suggestion
msgstr ""
```

2022-05-18 01:08 UTC, TheEvilSkeleton commented on po/he.po
> +msgstr "Martin Abente Lahaye"
```suggestion
msgstr ""
```

2022-05-27 20:15 UTC, yarons commented
Usually it breaks the statistics so I'm just copying the source but since you prefer it like that I don't care.

2022-05-28 00:48 UTC, tchx84 requested changes
hey @yarons , a few strings were added to the POT file sine you created this PR, mind updating as well?

2022-05-28 08:10 UTC, yarons commented
Rebased, is that OK?

2022-07-05 22:28 UTC, tchx84 requested changes
@yarons yeah, it's now including the missing strings. The only thing left is to add `he` to the `LINGUAS` file.

2022-07-06 13:30 UTC, yarons commented
@tchx84 Sure, done, thanks.

2022-07-06 23:08 UTC, merged

2022-07-06 23:08 UTC, tchx84 commented
Thank you!