po: Fix more Chinese translation
tchx84/Flatseal pull request #453
Opened 2022-06-08 03:10 UTC by EricZhang456

I blame all of these on fcitx5

2022-06-30 20:30 UTC, tchx84 requested changes

2022-06-30 20:30 UTC, tchx84 commented on po/zh_CN.po
> +msgstr "显示快速帮助" # I really don't know how to do this one. OG sounds weird.
It's fine, but please remove the # comment

2022-07-02 13:10 UTC, tchx84 approved these changes

2022-07-02 13:11 UTC, tchx84 commented
@EricZhang456 it seems this file is in conflict with the current version of the file, can rebase your changes on top of the latest version of this file?

2022-07-03 00:50 UTC, EricZhang456 commented
Huh. GitHub doesn't report any conflicts

2022-07-03 13:58 UTC, tchx84 commented
![image](https://user-images.githubusercontent.com/481418/177043122-f37e0f4f-248c-4832-a527-dfad35f9d721.png)

:cry:

2022-07-03 13:59 UTC, merged

2022-07-03 14:00 UTC, tchx84 commented
nvm.. it seems squashing did work!