po: Add Tamil translation
tchx84/Flatseal pull request #474
Opened 2022-09-27 02:55 UTC by kbdharun

Reopened PR, Sorry for the error in the previous PR.
Ref: #469

2022-09-27 02:56 UTC, kbdharun commented
Is it fine now @tchx84?

2022-09-28 12:38 UTC, tchx84 requested changes
Almost there!

2022-09-28 12:38 UTC, tchx84 commented on po/ta.po
> +msgstr "மார்டின் அபென்டே லஹயே"
This string is still translated :thinking:

2022-09-28 12:38 UTC, tchx84 commented on po/ta.po
> +msgstr "_ பிளாட்சீல் பற்றி"
By any chance, have you tested if these underscores do actually work? e.g. 

1. Open Flatseal with your translation.
2. Open the main menu
3. Long press Alt
4. Check if the menu items are highlighted for keyboard activation
5. Check if the menu items can be activated with the keyboard

2022-09-28 12:40 UTC, kbdharun commented on po/ta.po
> +msgstr "மார்டின் அபென்டே லஹயே"
Oh, Sorry, I used Poedit during translation, I didn't notice the messages.I will review it once again and make the necessary changes.

2022-09-28 12:41 UTC, kbdharun commented on po/ta.po
> +msgstr "_ பிளாட்சீல் பற்றி"
I will give it a try and I will update here.

2022-09-28 12:55 UTC, tchx84 commented
@kbdharun let me know if you're having troubles testing it, you should only include the .po files. The .mo files are created when the application builds.

2022-09-28 12:56 UTC, kbdharun commented on po/ta.po
> +msgstr "%B %e, %Y"
Regarding this string is this fine or should I make it into `<full-month-name> <day-of-month>, <year-with-century>` 's Tamil equivalent?

2022-09-28 12:57 UTC, kbdharun commented
> @kbdharun let me know if you're having troubles testing it, you should only include the .po files. The .mo files are created when the application builds.

Yeah, I will try it now and I will let you know. Yeah, I don't include `.mo` files usually too. (Removed it)

2022-09-28 13:02 UTC, kbdharun commented
Update: The build succeeded in `gnome-builder`. I will test it out and I will update it here in 10 minutes.
![image](https://user-images.githubusercontent.com/26346867/192785289-0161ef41-7286-476b-8999-eaa021b64ceb.png)

2022-09-28 13:16 UTC, kbdharun commented
Hey, I exported the bundle and installed the flatpak but I am unable to see the tamil translation from ta.po file even if I am in ta locale in system language.

2022-09-28 13:25 UTC, tchx84 commented
@kbdharun oh, one thing I noticed it's missing, is that you need to add your language code to po/LINGUAS file, and commit the change.

Re. testing this:
1. Make sure your changes are committed to your branch.
2. While on your branch, build Flatseal following these steps https://github.com/tchx84/Flatseal#build-it-yourself
3. Run Flatseal with `LC_ALL=ta_IN.UTF-8 flatpak --user run --branch=master com.github.tchx84.Flatseal`

2022-09-28 13:32 UTC, kbdharun commented
What Platform do I choose, I am running on `Fedora Workstation 36` in GNOME 42.

I am getting this error

```bash
[dharunkrishna@dharun-fedora-laptop Flatseal]$ flatpak --user install org.gnome.{Platform,Sdk}
Looking for matches…
error: No remote refs found similar to ‘org.gnome.Platform’
```

2022-09-28 13:35 UTC, tchx84 commented
> What Platform do I choose, I am running on `Fedora Workstation 36` in GNOME 42.
> 
> I am getting this error
> 
> ```shell
> [dharunkrishna@dharun-fedora-laptop Flatseal]$ flatpak --user install org.gnome.{Platform,Sdk}
> Looking for matches…
> error: No remote refs found similar to ‘org.gnome.Platform’
> ```

It seems you don't have Flathub installed? Try this

```
flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```

2022-09-28 13:40 UTC, kbdharun commented
Installed it thanks, I will test it out and will reply soon.

2022-09-28 13:52 UTC, kbdharun commented
Update: Everything works perfectly 🎉 ❤️ 

## Images for reference:

![Screenshot from 2022-09-28 19-16-40](https://user-images.githubusercontent.com/26346867/192796283-663a25e8-8209-41b3-81e1-51645b9e743c.png)

![Screenshot from 2022-09-28 19-16-40](https://user-images.githubusercontent.com/26346867/192796381-1e3be894-4f36-4caa-b974-7ffda97aadf0.png)

![Screenshot from 2022-09-28 19-16-55](https://user-images.githubusercontent.com/26346867/192796407-0631a426-4581-4ce0-ba61-4c061c40412e.png)

![Screenshot from 2022-09-28 19-17-05](https://user-images.githubusercontent.com/26346867/192796435-c901c725-e31d-430a-9df3-fef85dde48b9.png)

![Screenshot from 2022-09-28 19-17-17](https://user-images.githubusercontent.com/26346867/192796470-e1057aed-b123-4a14-a1ca-f460f87aa711.png)

![Screenshot from 2022-09-28 19-17-28](https://user-images.githubusercontent.com/26346867/192796498-a37669ba-d744-4ab0-94ce-dc67c8a83f90.png)

![Screenshot from 2022-09-28 19-17-36](https://user-images.githubusercontent.com/26346867/192796526-5fa0d52e-d86a-4d5e-bd26-db405f281e96.png)

![Screenshot from 2022-09-28 19-17-42](https://user-images.githubusercontent.com/26346867/192796568-b718f05f-60c4-44f9-b12b-e7b2d669505e.png)

![Screenshot from 2022-09-28 19-18-08](https://user-images.githubusercontent.com/26346867/192796815-26dc0d20-4bda-4014-8873-9f7e01a421b8.png)

2022-09-28 13:55 UTC, kbdharun commented
I have some questions
1. Can the documentation section be translated too in the future?
2. Also just out of curiosity, Are there any plans to port `Flatseal` to **GTK 4**?

2022-09-28 13:59 UTC, tchx84 commented
> Update: Everything works perfectly tada heart @tchx84

Excellent! Last ask, can you unify all commits (except the aboutDialog one) into the first commit? So we only have 2 commits like before.

2022-09-28 14:00 UTC, tchx84 commented
> I have some questions
> 
> 1. Can the documentation section be translated too in the future?

Yeah, it's in my plans. But it will also depends on translators time, of course.

> 2. Also just out of curiosity, Are there any plans to port `Flatseal` to **GTK 4**?

Yup, there's already a PR for that. but, there's still a few issues to be solved before we can merge it.

2022-09-28 14:04 UTC, kbdharun commented
> > Update: Everything works perfectly tada heart @tchx84
> 
> Excellent! Last ask, can you unify all commits (except the aboutDialog one) into the first commit? So we only have 2 commits like before.

Is it like `git rebase`? Can you tell me how to do it.

2022-09-28 14:08 UTC, tchx84 commented
> > > Update: Everything works perfectly tada heart @tchx84
> > 
> > 
> > Excellent! Last ask, can you unify all commits (except the aboutDialog one) into the first commit? So we only have 2 commits like before.
> 
> Is it like `git rebase`? Can you tell me how to do it.

try this..

```
git rebase -i a56fc8756d3f2d6671a4133fe0f8a039ba9d475f~
# then move the last 3 commits under the first one, and mark the ones you moved as "fixup".
```

After that, you should have only 2 commits, the first one (with all the changes under po/) and then the second commit with the change to aboutDialog.

2022-09-28 14:20 UTC, kbdharun commented
Done 🎉 , Thanks for your insights.

2022-09-28 14:33 UTC, tchx84 approved these changes

2022-09-28 14:33 UTC, merged

2022-09-28 14:34 UTC, tchx84 commented
@kbdharun ty!