Fix errors with AppStream 1.0
tchx84/Flatseal pull request #617
Opened 2023-11-26 20:08 UTC by yselkowitz

AppStream 1.0.0 includes several API breaks compared to the previous 0.16 (and earlier) versions, but unfortunately both versions used the same 1.0 GI version, so there is no way to differentiate at import time. As such, try/catch is used to fall back to the 0.16 API where they differ.

2023-12-13 19:49 UTC, tchx84 requested changes

2023-12-13 19:49 UTC, tchx84 commented on src/models/applications.js
> +        }
Thanks for working on this, can you please modify this to assume it's running with AppStream 1.0.0+  only? (no try-except block, no back-compatibility).

I will merge it once the gnome runtime bumps AppStream to that version and, in the meantime, you should contact whoever is distributing flatseal outside of flathub to patch this downstream.

Version guessing is not something I want upstream.

2023-12-25 21:00 UTC, darkblaze69 commented
with this patch I still get an error with failing launch

`JS ERROR: TypeError: component.get_developer_name is not a function`

2023-12-28 15:55 UTC, tchx84 approved these changes
This looks much better, thanks. I will merge this as soon as GNOME runtime upgrades too.

2024-02-07 15:38 UTC, C0rn3j commented
@tchx84 is this still waiting for a runtime upgrade?

Just had to include this in [AUR/flatseal](https://aur.archlinux.org/packages/flatseal) because of the crash on `component.get_developer()`.

2024-02-07 16:50 UTC, tchx84 commented
> @tchx84 is this still waiting for a runtime upgrade?
> 
> Just had to include this in [AUR/flatseal](https://aur.archlinux.org/packages/flatseal) because of the crash on `component.get_developer()`.

Yes, this change is still waiting for the runtime upgrade. Be assured that this will be merged once it happens. Please let me know if notice anything else.

2024-03-20 16:28 UTC, tchx84 commented
Unfortunately, GNOME 46 still ships with older appstream version.

```
$ flatpak run --command=appstreamcli org.gnome.Sdk//46 --version
AppStream version: 0.16.4
```

2024-03-20 22:34 UTC, C0rn3j commented
Forgive if I am misunderstanding something here.

Wouldn't it be a better idea to pull this, making the places that do not support the current stable API run into issues, making them figure out there is a new stable API and having to apply workarounds?

Currently it's exactly the other way around, which seems to be punishing those who ship the current stable release.

2024-04-18 22:44 UTC, C0rn3j commented
This now conflicts after the 2.2.0 release.

2024-09-18 06:44 UTC, TheComputerGuy96 commented
GNOME 47 runtime has just been released: https://gitlab.gnome.org/GNOME/gnome-build-meta/-/tags/47.0 (so this MR can finally move forward)

2024-09-18 20:15 UTC, tchx84 commented
@yselkowitz thanks for the patience , merged with https://github.com/tchx84/Flatseal/pull/710

2024-09-18 20:15 UTC, closed without merging