Create sv.po
tchx84/Flatseal pull request #69
Opened 2020-05-04 05:18 UTC by eson57

Hi,
Here's Swedish translation if wanted.

![ksnip_2020-05-04_071320](https://user-images.githubusercontent.com/2996154/80937945-6f1edc80-8dd7-11ea-843c-014b20df0f31.png)

2020-05-04 22:16 UTC, tchx84 requested changes
Thanks a lot Åke, just one comment.

2020-05-04 22:16 UTC, tchx84 commented on po/sv.po
> +msgstr "Flatseal"
Please note the `#. TRANSLATORS: Don't translate this text`. You can leave it empty, e.g.

```
msgid "Flatseal"
msgstr ""
```

2020-05-04 22:32 UTC, tchx84 commented
Let me know if you need any help.

2020-05-05 03:40 UTC, eson57 commented
Done!
Sorry, I don't see that comment using PoEdit and I also don't see how it matters as long as don't translate.

2020-05-06 02:09 UTC, tchx84 approved these changes

2020-05-06 02:10 UTC, tchx84 commented
Thanks Åke!

2020-05-06 02:10 UTC, merged